### ISSUE TITLE
Link reporting a problem in gluster on https://www.gluster.org/community/ point to itself

### ISSUE THREAD

**Issue by mscherer** [gluster/glusterweb#161]
On https://www.gluster.org/community/ , there is a icon "report a problem to gluster, open a new bug" (in the green zone, 3rd white square). The link return to the top of the page itself, which is not exactly clear or helpful, and should likely go to bugzilla directly.

**Comment by mscherer** [comment]
In fact, the 4 squares do go the same link, despites looking like outgoing links. I suspect something is broken, as I can reproduce the issue on Firefox and Chromium on RHEL 7.

The source code do not show 'a' tags, and I do not see why there is a link (maybe some css side effect)

**Comment by amye** [comment]
Something is broken because in the actual backend, they link to:
"Source Code" > "https://github.com/gluster/glusterfs"
"Bug Tracking" > https://bugzilla.redhat.com/enter_bug.cgi?product=GlusterFS
"Report a problem in Gluster" > https://bugzilla.redhat.com/enter_bug.cgi?product=GlusterFS
"Report a problem in Documentation" > https://github.com/gluster/glusterdocs/issues/new

**Comment by amye** [comment]
@jasonbrooks has the right of this one, it was advanced custom fields being overly aggressive.
