### ISSUE TITLE
Thought for the Consultants page → highlight the organisations who contribute

### ISSUE THREAD

**Issue by justinclift** [gluster/glusterweb#8]
With the Consultants page, it is kind of difficult for a person-not-already-familiar-with-our-Community to know which companies are contributors or not:

&nbsp; &nbsp; http://www.gluster.org/consultants/

It might be a good idea to have something (gold star with link/hover text?) to indicate the companies putting time into developing the Gluster Community (in whatever form).

**Comment by amye** [comment]
We actually need to come back to this page and add things like, oh, you know, Red Hat  - in here. 
Taking this as an Action Item.

**Comment by justinclift** [comment]
:smile:

**Comment by tigert** [comment]
I can help you with the layout and graphics, but I would need the content: what would be the contact point etc for Red Hat.

I think it would be also good to have instructions to have your company included to the list. We could do an automatic listing with yaml data, but maybe this is overkill at this point. So perhaps a list of information to include and a simple snippet for ourselves to put in for new entries.

I can look into the design so that it would scale better - maybe a list with one column or maybe two.

**Comment by amye** [comment]
Update: 
After review with the Storage marketing team, the best place to point Red Hat support inquiries is http://www.redhat.com/en/technologies/storage/gluster 

Tigert, can we touch base on this tomorrow?

**Comment by tigert** [comment]
#57 has the beginnings. I'll make an entry for Red Hat based on the above url. Thanks!

If someone wants to add their company to the list, where should they direct their query? Through a pull request? :-)

**Comment by amye** [comment]
We now have the layout changed to accept new consultants, so yes, new PRs accepted. :dancers:
